version: "3.8"
services:
backend:
build: ./backend
ports:
 - "8000:8000"
environment:
 - DATABASE_URL=postgresql://admin:secret@db:5432/gym
depends_on:
 - db
frontend:
build: ./frontend
ports:
 - "3000:3000"
db:
image: postgres:latest
environment:
 - POSTGRES_DB=gym
 - POSTGRES_USER=admin
 - POSTGRES_PASSWORD=secret
volumes:
 - postgres_data:/var/lib/postgresql/data
volumes:
postgres_data:

